// This file is generated by src/actors/_scripts/generate-actor-migrations.ts.
// Source of truth is drizzle-kit output under ./drizzle (meta/_journal.json + *.sql).
// Do not hand-edit this file.

const journal = {
  "entries": [
    {
      "idx": 0,
      "when": 1770924376525,
      "tag": "0000_rare_iron_man",
      "breakpoints": true
    },
    {
      "idx": 1,
      "when": 1770947252912,
      "tag": "0001_sleepy_lady_deathstrike",
      "breakpoints": true
    },
    {
      "idx": 2,
      "when": 1772668800000,
      "tag": "0002_tiny_silver_surfer",
      "breakpoints": true
    }
  ]
} as const;

export default {
  journal,
  migrations: {
    m0000: `CREATE TABLE \`provider_profiles\` (
	\`provider_id\` text PRIMARY KEY NOT NULL,
	\`profile_json\` text NOT NULL,
	\`updated_at\` integer NOT NULL
);
`,
    m0001: `CREATE TABLE \`repos\` (
	\`repo_id\` text PRIMARY KEY NOT NULL,
	\`remote_url\` text NOT NULL,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
`,
    m0002: `CREATE TABLE \`handoff_lookup\` (
	\`handoff_id\` text PRIMARY KEY NOT NULL,
	\`repo_id\` text NOT NULL
);
`,
  } as const
};
