/// GStreamer WebRTC pipeline for desktop streaming.
///
/// Creates a pipeline that captures the X11 display via `ximagesrc`, encodes to
/// VP8, and streams over WebRTC using `webrtcbin`. Signaling (SDP offer/answer,
/// ICE candidate exchange) is handled via channels that the caller bridges to
/// the client WebSocket.
#[cfg(feature = "desktop-gstreamer")]
pub mod pipeline {
    use gstreamer as gst;
    use gstreamer::prelude::*;
    use gstreamer_sdp as gst_sdp;
    use gstreamer_webrtc as gst_webrtc;
    use tokio::sync::mpsc;

    /// Messages sent from the GStreamer pipeline to the WebSocket handler.
    #[derive(Debug)]
    pub enum PipelineEvent {
        /// SDP offer generated by webrtcbin.
        Offer(String),
        /// ICE candidate produced by webrtcbin.
        IceCandidate {
            candidate: String,
            sdp_m_line_index: u32,
        },
    }

    /// Messages sent from the WebSocket handler to the GStreamer pipeline.
    #[derive(Debug)]
    pub enum SignalingCommand {
        /// SDP answer from the client.
        Answer(String),
        /// ICE candidate from the client.
        IceCandidate {
            candidate: String,
            sdp_m_line_index: u32,
        },
    }

    pub struct GStreamerPipeline {
        pipeline: gst::Pipeline,
        cmd_tx: mpsc::UnboundedSender<SignalingCommand>,
    }

    impl GStreamerPipeline {
        /// Create and start a new GStreamer WebRTC pipeline for the given display.
        ///
        /// Returns the pipeline handle and a receiver for pipeline events (offers,
        /// ICE candidates) that should be forwarded to the client.
        pub fn new(
            display: &str,
        ) -> Result<(Self, mpsc::UnboundedReceiver<PipelineEvent>), String> {
            gst::init().map_err(|e| {
                format!(
                    "Desktop streaming requires GStreamer. Install it with: \
                     sandbox-agent desktop install\n\
                     Error: {e}"
                )
            })?;

            let pipeline_str = format!(
                "ximagesrc display-name={display} use-damage=true show-pointer=true \
                 ! video/x-raw,framerate=30/1 \
                 ! videorate \
                 ! videoconvert \
                 ! queue max-size-buffers=1 leaky=downstream \
                 ! vp8enc deadline=1 target-bitrate=3000000 cpu-used=16 threads=4 \
                   keyframe-max-dist=60 end-usage=cbr buffer-size=500 buffer-initial-size=300 \
                   error-resilient=partitions \
                 ! rtpvp8pay picture-id-mode=15bit \
                 ! queue max-size-buffers=1 leaky=downstream \
                 ! application/x-rtp,media=video,encoding-name=VP8,payload=96 \
                 ! webrtcbin name=wb bundle-policy=max-bundle"
            );

            let pipeline = gst::parse::launch(&pipeline_str)
                .map_err(|e| format!("failed to create GStreamer pipeline: {e}"))?
                .downcast::<gst::Pipeline>()
                .map_err(|_| "pipeline is not a GstPipeline".to_string())?;

            let webrtcbin = pipeline
                .by_name("wb")
                .ok_or_else(|| "webrtcbin element not found in pipeline".to_string())?;

            // Configure STUN for ICE connectivity (used for server-reflexive
            // candidates when behind NAT).
            webrtcbin.set_property_from_str("stun-server", "stun://stun.l.google.com:19302");

            // Restrict the UDP port range so Docker port forwarding works.
            // The ice-agent is a GstWebRTCICE which wraps a NiceAgent.
            let ice_agent: gst::glib::Object = webrtcbin.property("ice-agent");
            // GstWebRTCNice has a "min-rtp-port" and "max-rtp-port" property
            // in newer versions, but on GStreamer 1.22 we need to access the
            // underlying NiceAgent via the "agent" property.
            if ice_agent.has_property("min-rtp-port", None) {
                ice_agent.set_property("min-rtp-port", 30000u32);
                ice_agent.set_property("max-rtp-port", 30100u32);
            } else if ice_agent.has_property("agent", None) {
                let nice_agent: gst::glib::Object = ice_agent.property("agent");
                nice_agent.set_property("max-port", 30100u32);
                nice_agent.set_property("min-port", 30000u32);
            }

            // Channel for pipeline -> WS handler events.
            let (event_tx, event_rx) = mpsc::unbounded_channel::<PipelineEvent>();

            // Channel for WS handler -> pipeline commands.
            let (cmd_tx, mut cmd_rx) = mpsc::unbounded_channel::<SignalingCommand>();

            // Note: Data channel for input will be created once we establish
            // the WebRTC connection. Input falls back to the WS transport.

            // When webrtcbin needs to negotiate, create an offer.
            let wb_clone = webrtcbin.clone();
            let event_tx_offer = event_tx.clone();
            webrtcbin.connect("on-negotiation-needed", false, move |_| {
                let wb_offer = wb_clone.clone();
                let wb_create = wb_clone.clone();
                let tx = event_tx_offer.clone();
                let promise = gst::Promise::with_change_func(move |reply| {
                    let reply = match reply {
                        Ok(Some(reply)) => reply,
                        _ => return,
                    };
                    let offer = match reply.value("offer") {
                        Ok(offer) => offer,
                        Err(_) => return,
                    };
                    let offer = offer
                        .get::<gst_webrtc::WebRTCSessionDescription>()
                        .expect("offer is WebRTCSessionDescription");
                    wb_offer.emit_by_name::<()>(
                        "set-local-description",
                        &[&offer, &None::<gst::Promise>],
                    );
                    if let Ok(sdp_text) = offer.sdp().as_text() {
                        let _ = tx.send(PipelineEvent::Offer(sdp_text.to_string()));
                    }
                });
                wb_create.emit_by_name::<()>("create-offer", &[&None::<gst::Structure>, &promise]);
                None
            });

            // When webrtcbin produces an ICE candidate, send it to client.
            // We rewrite host candidates to use 127.0.0.1 so the browser can
            // reach the server when running inside Docker.
            let event_tx_ice = event_tx;
            webrtcbin.connect("on-ice-candidate", false, move |values| {
                let sdp_m_line_index = values[1].get::<u32>().expect("m-line index is u32");
                let candidate = values[2].get::<String>().expect("candidate is String");

                // Only forward UDP host candidates, rewritten to 127.0.0.1.
                // Skip TCP candidates (browsers rarely use TCP for WebRTC media)
                // and server-reflexive candidates (STUN responses with public IPs).
                if candidate.contains("UDP") && candidate.contains("typ host") {
                    // Replace the Docker-internal IP with 127.0.0.1 so the
                    // browser on the host can connect.
                    let rewritten = rewrite_candidate_ip(&candidate, "127.0.0.1");
                    let _ = event_tx_ice.send(PipelineEvent::IceCandidate {
                        candidate: rewritten,
                        sdp_m_line_index,
                    });
                }

                None
            });

            // Start the pipeline.
            pipeline
                .set_state(gst::State::Playing)
                .map_err(|e| format!("failed to start GStreamer pipeline: {e}"))?;

            // Spawn a thread to process signaling commands from the WS handler.
            let wb_cmd = webrtcbin.clone();
            std::thread::spawn(move || {
                while let Some(cmd) = cmd_rx.blocking_recv() {
                    match cmd {
                        SignalingCommand::Answer(sdp_str) => {
                            let sdp = match gst_sdp::SDPMessage::parse_buffer(sdp_str.as_bytes()) {
                                Ok(sdp) => sdp,
                                Err(e) => {
                                    tracing::warn!(error = ?e, "failed to parse SDP answer");
                                    continue;
                                }
                            };
                            let answer = gst_webrtc::WebRTCSessionDescription::new(
                                gst_webrtc::WebRTCSDPType::Answer,
                                sdp,
                            );
                            wb_cmd.emit_by_name::<()>(
                                "set-remote-description",
                                &[&answer, &None::<gst::Promise>],
                            );
                        }
                        SignalingCommand::IceCandidate {
                            candidate,
                            sdp_m_line_index,
                        } => {
                            wb_cmd.emit_by_name::<()>(
                                "add-ice-candidate",
                                &[&sdp_m_line_index, &candidate],
                            );
                        }
                    }
                }
            });

            Ok((Self { pipeline, cmd_tx }, event_rx))
        }

        /// Send a signaling command to the pipeline.
        pub fn send_command(&self, cmd: SignalingCommand) {
            let _ = self.cmd_tx.send(cmd);
        }
    }

    impl Drop for GStreamerPipeline {
        fn drop(&mut self) {
            let _ = self.pipeline.set_state(gst::State::Null);
        }
    }

    /// Rewrite the IP address in an ICE candidate string.
    ///
    /// ICE candidate format:
    ///   candidate:1 1 UDP 2015363327 172.17.0.6 39395 typ host
    ///
    /// We replace the IP (field 5, 0-indexed) with the target IP.
    fn rewrite_candidate_ip(candidate: &str, target_ip: &str) -> String {
        let parts: Vec<&str> = candidate.splitn(6, ' ').collect();
        if parts.len() >= 6 {
            // parts[4] is the IP address
            let rest_after_ip = &candidate[parts[..5].join(" ").len()..];
            format!(
                "{} {} {} {} {}{}",
                parts[0], parts[1], parts[2], parts[3], target_ip, rest_after_ip
            )
        } else {
            candidate.to_string()
        }
    }
}

/// Check if GStreamer support is compiled in.
pub fn is_available() -> bool {
    cfg!(feature = "desktop-gstreamer")
}
