// This file is generated by src/actors/_scripts/generate-actor-migrations.ts.
// Source of truth is drizzle-kit output under ./drizzle (meta/_journal.json + *.sql).
// Do not hand-edit this file.

const journal = {
  entries: [
    {
      idx: 0,
      when: 1773376221848,
      tag: "0000_useful_la_nuit",
      breakpoints: true,
    },
  ],
} as const;

export default {
  journal,
  migrations: {
    m0000: `CREATE TABLE \`repo_meta\` (
	\`id\` integer PRIMARY KEY NOT NULL,
	\`remote_url\` text NOT NULL,
	\`updated_at\` integer NOT NULL,
	CONSTRAINT \`repo_meta_singleton_id_check\` CHECK(\`id\` = 1)
);
--> statement-breakpoint
CREATE TABLE \`task_index\` (
	\`task_id\` text PRIMARY KEY NOT NULL,
	\`branch_name\` text,
	\`created_at\` integer NOT NULL,
	\`updated_at\` integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`tasks\` (
	\`task_id\` text PRIMARY KEY NOT NULL,
	\`repo_id\` text NOT NULL,
	\`title\` text NOT NULL,
	\`status\` text NOT NULL,
	\`repo_name\` text NOT NULL,
	\`updated_at_ms\` integer NOT NULL,
	\`branch\` text,
	\`pull_request_json\` text,
	\`sessions_summary_json\` text DEFAULT '[]' NOT NULL
);
`,
  } as const,
};
